services:
  backend:
    build: .
    container_name: todo_api_container

    env_file: ".env"

    ports:
      - ${PORT}:${PORT}

    command: >
      sh -c "ln -snf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime &&
      echo ${TIME_ZONE} > /etc/timezone && npm start"

    volumes:
      - E:/LeapFrog/WEEK7/node_assignment_1:/app

  database:
    image: postgres:16
    container_name: postgres_todo
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: always

volumes:
  postgres_data:
